---
- hosts: server2.abc.com
  remote_user: test
  become: yes
  tasks:
     - name: install httpd package
       yum: name=httpd state=installed
     - name: copy index.html
       copy: src=index.html dest=/var/www/html
       notify: restart httpd service
     - name: start the httpd service
       service:  name=httpd state=started
  handlers:
     - name: restart httpd service
       service: name=httpd state=restarted
  
